version: "3.3"

services: 
  frontend:
    image: wpracr1.azurecr.io/frontend:prod
    build: 
      context: ./frontend
    command: yarn build
    volumes:
      - front:/app/dist
    container_name: frontend

  server:
    image: wpracr1.azurecr.io/server:prod
    build: 
      context: ./server
    # env_file:
    #   - .env
    volumes:
      - front:/app/public
    ports:
      - 80:80
    container_name: server

volumes:
  front:
    # driver: azure_file
    # driver_opts:
    #   share_name: wprfile
    #   storage_account_name: wprshare
